---
title: "7 - Survival Analysis"
author: "DrPH Yr 1 Sem 1 2019/2020"
date: "14/12/2019"
output: 
  html_document:
    toc: yes
    toc_float:
      collapsed: no
---

# Dataset


```{r}
library(pacman)
p_load(haven, foreign, broom, tidyverse, psych, knitr, lubridate, survival, survminer)
mydata <- read_dta("stroke_outcome.dta")
mydata <- mydata %>%
  mutate_if(is.labelled, ~as_factor(.))
mydata <- mydata %>%
  mutate(dur = mydata$doa %--% mydata$dod) %>%
  mutate(dur = as.duration(dur)) %>%
  mutate(dur_days = dur/ddays(1))
```


Dataset stroke_outcome.dta had these variables

- ID : unique identification number
- sex : patient's gender (male/female)
- race : ethnicity (malay/chinese)
- doa : date of admission
- dod : date of discharge
- gcs : GCS score
- sbp : systolic BP
- dbp : diasolic BP
- age : age of patient during admission (in years)
- event : outcome of patient during date of discharge (censored/dead)
- dm2 : DM status (no/yes)
- hpt2 : Hpt status (no/yes)
- race2 : Malay Ethnicity (no/yes)

# Question 1

Explain the KM Estimation for the survival of the stroke patient

# Question 2

Explain the KM Estimation for the survival of the stroke patient, by DM status (variable:dm2)

# Question 3

Analyse the relationship between variable "event" and these covariate, "sex", "gcs", "sbp" and "age". name the model as "mod.metab".

Write the estimated regression parameter in a table based on "mod.metab"

Interpret the parameter


# Question 4

Add an interaction term between variable "sex" and "gcs" to the model "mod.metab". Run the analysis and name the model as "mod.metab.int"

Write the estimated regression parameters in a table based on "mod.metab.int"


# Question 5

Compare model "mod.metab.int" and "mod.metab" using an approprite test and interpret the result


# Question 6

Predict probability survival at 14 days when sex = female, gcs = 10, sbp = 110 and age = 75, based on "mod.metab" and "mod.metab.int", as compared to the population average.
